import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";

const poppins = Poppins({
  weight: ["400", "500", "600" , "700", "900"],   
  display: "swap",
  subsets: ["latin"],
  variable: "--poppins-font",
});

export const metadata = {
  title: "Rebel Rover",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <NavBar/>
      {children}
      <Footer/>
      </body>
    </html>
  );
}
